apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "payment-platform.fullname" . }}-runtime
  labels:
    {{- include "payment-platform.labels" . | nindent 4 }}
data:
  DEPLOYMENT_ENVIRONMENT: {{ .Values.global.environment | quote }}
  KAFKA_BOOTSTRAP_SERVERS: {{ .Values.global.kafkaBootstrapServers | quote }}
  REDIS_HOST: {{ .Values.global.redisHost | quote }}
  REDIS_PORT: {{ .Values.global.redisPort | quote }}
  JWT_ISSUER_URI: {{ .Values.global.jwtIssuerUri | quote }}
  JWT_JWK_SET_URI: {{ .Values.global.jwtJwkSetUri | quote }}
  TRACING_SAMPLING_PROBABILITY: {{ .Values.global.tracingSamplingProbability | quote }}
  OTEL_TRACING_ENABLED: {{ .Values.global.otelTracingEnabled | quote }}
  OTEL_EXPORTER_OTLP_TRACES_ENDPOINT: {{ .Values.global.otelTracesEndpoint | quote }}
  OBSERVABILITY_PUBLIC_PROMETHEUS: {{ .Values.global.observabilityPublicPrometheus | quote }}
  MANAGEMENT_ENDPOINT_HEALTH_PROBES_ENABLED: "true"
  SERVER_SHUTDOWN: graceful
  SPRING_LIFECYCLE_TIMEOUT_PER_SHUTDOWN_PHASE: 20s
