{{- if .Values.serviceAccount.create }}
{{- if .Values.serviceAccount.perService }}
{{- range $name, $svc := .Values.services }}
{{- if $svc.enabled }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "payment-platform.serviceAccountName" (dict "root" $ "name" $name) }}
  labels:
    {{- include "payment-platform.labels" $ | nindent 4 }}
    app.kubernetes.io/component: {{ $name }}
automountServiceAccountToken: false
---
{{- end }}
{{- end }}
{{- else }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "payment-platform.serviceAccountName" (dict "root" . "name" "shared") }}
  labels:
    {{- include "payment-platform.labels" . | nindent 4 }}
automountServiceAccountToken: false
{{- end }}
{{- end }}
