{{- if .Values.serviceAccount.create }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "payment-platform.serviceAccountName" . }}
  labels:
    {{- include "payment-platform.labels" . | nindent 4 }}
automountServiceAccountToken: false
{{- end }}
